import express from "express";
import cors from "cors";
import userRouter from "./routes/user.route.js";
import path from "path";
import adminRouter from "./routes/admin.route.js";
const app = express();
app.use(cors());
app.use(express.json());
console.log(process.cwd());
console.log(path.join(process.cwd(), "/src/uploads"));
app.use("/uploads", express.static(path.join(process.cwd(), "/src/uploads")));
app.use(express.urlencoded({ extended: true }));
app.use("/api/users", userRouter);
app.use("/admin", adminRouter);
export default app;
